/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.skype;

public class BetterTogetherTransportModuleJNI {
  public final static native long new_EndpointList__SWIG_0();
  public final static native long new_EndpointList__SWIG_1(long jarg1, EndpointList jarg1_);
  public final static native long EndpointList_capacity(long jarg1, EndpointList jarg1_);
  public final static native void EndpointList_reserve(long jarg1, EndpointList jarg1_, long jarg2);
  public final static native boolean EndpointList_isEmpty(long jarg1, EndpointList jarg1_);
  public final static native void EndpointList_clear(long jarg1, EndpointList jarg1_);
  public final static native long new_EndpointList__SWIG_2(int jarg1, long jarg2, IBTTransportEndpoint jarg2_);
  public final static native int EndpointList_doSize(long jarg1, EndpointList jarg1_);
  public final static native void EndpointList_doAdd__SWIG_0(long jarg1, EndpointList jarg1_, long jarg2, IBTTransportEndpoint jarg2_);
  public final static native void EndpointList_doAdd__SWIG_1(long jarg1, EndpointList jarg1_, int jarg2, long jarg3, IBTTransportEndpoint jarg3_);
  public final static native long EndpointList_doRemove(long jarg1, EndpointList jarg1_, int jarg2);
  public final static native long EndpointList_doGet(long jarg1, EndpointList jarg1_, int jarg2);
  public final static native long EndpointList_doSet(long jarg1, EndpointList jarg1_, int jarg2, long jarg3, IBTTransportEndpoint jarg3_);
  public final static native void EndpointList_doRemoveRange(long jarg1, EndpointList jarg1_, int jarg2, int jarg3);
  public final static native void delete_EndpointList(long jarg1);
  public final static native void delete_IBTTransportEndpoint(long jarg1);
  public final static native void IBTTransportEndpoint_setupSession(long jarg1, IBTTransportEndpoint jarg1_, String jarg2, String jarg3, String jarg4, long jarg5, IOutgoingCommandResponse jarg5_);
  public final static native void IBTTransportEndpoint_sendCommand(long jarg1, IBTTransportEndpoint jarg1_, String jarg2, String jarg3, String jarg4, long jarg5, IOutgoingCommandResponse jarg5_);
  public final static native String IBTTransportEndpoint_getEndpointId(long jarg1, IBTTransportEndpoint jarg1_);
  public final static native int IBTTransportEndpoint_getEndpointType(long jarg1, IBTTransportEndpoint jarg1_);
  public final static native int IBTTransportEndpoint_getEndpointState(long jarg1, IBTTransportEndpoint jarg1_);
  public final static native void IBTTransportEndpoint_setSessionEstablished(long jarg1, IBTTransportEndpoint jarg1_, boolean jarg2);
  public final static native void delete_IBTTransportUser(long jarg1);
  public final static native void delete_IBTTransportUser_IAuthTokenCallback(long jarg1);
  public final static native void IBTTransportUser_IAuthTokenCallback_onTokenRequired(long jarg1, IBTTransportUser.IAuthTokenCallback jarg1_, String jarg2);
  public final static native long new_IBTTransportUser_IAuthTokenCallback();
  public final static native void IBTTransportUser_IAuthTokenCallback_director_connect(IBTTransportUser.IAuthTokenCallback obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void IBTTransportUser_IAuthTokenCallback_change_ownership(IBTTransportUser.IAuthTokenCallback obj, long cptr, boolean take_or_release);
  public final static native long IBTTransportUser_discover(long jarg1, IBTTransportUser jarg1_);
  public final static native void IBTTransportUser_updateAuthToken(long jarg1, IBTTransportUser jarg1_, String jarg2);
  public final static native long IBTTransportUser_getEndpoints(long jarg1, IBTTransportUser jarg1_);
  public final static native void delete_IBTTransportUser_IIncomingCommandListener(long jarg1);
  public final static native void IBTTransportUser_IIncomingCommandListener_onCommandReceived(long jarg1, IBTTransportUser.IIncomingCommandListener jarg1_, long jarg2, IIncomingCommandRequest jarg2_, long jarg3, IIncomingCommandResponse jarg3_);
  public final static native long new_IBTTransportUser_IIncomingCommandListener();
  public final static native void IBTTransportUser_IIncomingCommandListener_director_connect(IBTTransportUser.IIncomingCommandListener obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void IBTTransportUser_IIncomingCommandListener_change_ownership(IBTTransportUser.IIncomingCommandListener obj, long cptr, boolean take_or_release);
  public final static native String StackInfo_uiVersion_get(long jarg1, StackInfo jarg1_);
  public final static native String StackInfo_platform_get(long jarg1, StackInfo jarg1_);
  public final static native String StackInfo_appId_get(long jarg1, StackInfo jarg1_);
  public final static native String StackInfo_languageId_get(long jarg1, StackInfo jarg1_);
  public final static native long new_StackInfo__SWIG_0(String jarg1, String jarg2, String jarg3, String jarg4);
  public final static native long new_StackInfo__SWIG_1(String jarg1, String jarg2, String jarg3);
  public final static native long new_StackInfo__SWIG_2(String jarg1, String jarg2);
  public final static native long new_StackInfo__SWIG_3(String jarg1);
  public final static native long new_StackInfo__SWIG_4();
  public final static native void delete_StackInfo(long jarg1);
  public final static native String UserInfo_endpointId_get(long jarg1, UserInfo jarg1_);
  public final static native String UserInfo_userId_get(long jarg1, UserInfo jarg1_);
  public final static native String UserInfo_token_get(long jarg1, UserInfo jarg1_);
  public final static native String UserInfo_tenant_get(long jarg1, UserInfo jarg1_);
  public final static native String UserInfo_ring_get(long jarg1, UserInfo jarg1_);
  public final static native long new_UserInfo__SWIG_0(String jarg1, String jarg2, String jarg3, String jarg4, String jarg5);
  public final static native long new_UserInfo__SWIG_1(String jarg1, String jarg2, String jarg3, String jarg4);
  public final static native long new_UserInfo__SWIG_2(String jarg1, String jarg2, String jarg3);
  public final static native long new_UserInfo__SWIG_3(String jarg1, String jarg2);
  public final static native long new_UserInfo__SWIG_4(String jarg1);
  public final static native long new_UserInfo__SWIG_5();
  public final static native void delete_UserInfo(long jarg1);
  public final static native void delete_IBTTransportStack(long jarg1);
  public final static native void IBTTransportStack_createBTTransportStack(long jarg1, long jarg2, long jarg3, long jarg4, StackInfo jarg4_);
  public final static native long IBTTransportStack_getBTTransportStack();
  public final static native void IBTTransportStack_destroyBTTransportStack();
  public final static native long IBTTransportStack_getBTTransportUser(long jarg1, IBTTransportStack jarg1_, long jarg2, long jarg3, IBTTransportUser.IAuthTokenCallback jarg3_, long jarg4, IBTTransportUser.IIncomingCommandListener jarg4_, int jarg5, long jarg6, UserInfo jarg6_);
  public final static native void delete_IOutgoingCommandResponse(long jarg1);
  public final static native void IOutgoingCommandResponse_onRequestSucceeded(long jarg1, IOutgoingCommandResponse jarg1_, String jarg2, String jarg3);
  public final static native void IOutgoingCommandResponse_onRequestFailed(long jarg1, IOutgoingCommandResponse jarg1_, String jarg2, int jarg3, String jarg4);
  public final static native long new_IOutgoingCommandResponse();
  public final static native void IOutgoingCommandResponse_director_connect(IOutgoingCommandResponse obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void IOutgoingCommandResponse_change_ownership(IOutgoingCommandResponse obj, long cptr, boolean take_or_release);
  public final static native void delete_IIncomingCommandRequest(long jarg1);
  public final static native String IIncomingCommandRequest_getEndpointId(long jarg1, IIncomingCommandRequest jarg1_);
  public final static native String IIncomingCommandRequest_getCommand(long jarg1, IIncomingCommandRequest jarg1_);
  public final static native String IIncomingCommandRequest_getCommandDetails(long jarg1, IIncomingCommandRequest jarg1_);
  public final static native String IIncomingCommandRequest_getCauseId(long jarg1, IIncomingCommandRequest jarg1_);
  public final static native long IIncomingCommandRequest_getSequenceNumber(long jarg1, IIncomingCommandRequest jarg1_);
  public final static native void delete_IIncomingCommandResponse(long jarg1);
  public final static native void IIncomingCommandResponse_setStatus(long jarg1, IIncomingCommandResponse jarg1_, long jarg2);
  public final static native void IIncomingCommandResponse_setBody(long jarg1, IIncomingCommandResponse jarg1_, String jarg2);
  public final static native int IIncomingCommandResponse_send(long jarg1, IIncomingCommandResponse jarg1_);

  public static void SwigDirector_IBTTransportUser_IAuthTokenCallback_onTokenRequired(IBTTransportUser.IAuthTokenCallback jself, String oldToken) {
    jself.onTokenRequired(oldToken);
  }
  public static void SwigDirector_IBTTransportUser_IIncomingCommandListener_onCommandReceived(IBTTransportUser.IIncomingCommandListener jself, long arg0, long arg1) {
    jself.onCommandReceived((arg0 == 0) ? null : new IIncomingCommandRequest(arg0, true), (arg1 == 0) ? null : new IIncomingCommandResponse(arg1, true));
  }
  public static void SwigDirector_IOutgoingCommandResponse_onRequestSucceeded(IOutgoingCommandResponse jself, String causeId, String responseBody) {
    jself.onRequestSucceeded(causeId, responseBody);
  }
  public static void SwigDirector_IOutgoingCommandResponse_onRequestFailed(IOutgoingCommandResponse jself, String causeId, int errorCode, String errorDetails) {
    jself.onRequestFailed(causeId, errorCode, errorDetails);
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
