/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.skype;

public class EndpointList extends java.util.AbstractList<IBTTransportEndpoint> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EndpointList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EndpointList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BetterTogetherTransportModuleJNI.delete_EndpointList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public EndpointList(IBTTransportEndpoint[] initialElements) {
    this();
    reserve(initialElements.length);

    for (IBTTransportEndpoint element : initialElements) {
      add(element);
    }
  }

  public EndpointList(Iterable<IBTTransportEndpoint> initialElements) {
    this();
    for (IBTTransportEndpoint element : initialElements) {
      add(element);
    }
  }

  public IBTTransportEndpoint get(int index) {
    return doGet(index);
  }

  public IBTTransportEndpoint set(int index, IBTTransportEndpoint e) {
    return doSet(index, e);
  }

  public boolean add(IBTTransportEndpoint e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, IBTTransportEndpoint e) {
    modCount++;
    doAdd(index, e);
  }

  public IBTTransportEndpoint remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public EndpointList() {
    this(BetterTogetherTransportModuleJNI.new_EndpointList__SWIG_0(), true);
  }

  public EndpointList(EndpointList other) {
    this(BetterTogetherTransportModuleJNI.new_EndpointList__SWIG_1(EndpointList.getCPtr(other), other), true);
  }

  public long capacity() {
    return BetterTogetherTransportModuleJNI.EndpointList_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    BetterTogetherTransportModuleJNI.EndpointList_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return BetterTogetherTransportModuleJNI.EndpointList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    BetterTogetherTransportModuleJNI.EndpointList_clear(swigCPtr, this);
  }

  public EndpointList(int count, IBTTransportEndpoint value) {
    this(BetterTogetherTransportModuleJNI.new_EndpointList__SWIG_2(count, IBTTransportEndpoint.getCPtr(value), value), true);
  }

  private int doSize() {
    return BetterTogetherTransportModuleJNI.EndpointList_doSize(swigCPtr, this);
  }

  private void doAdd(IBTTransportEndpoint x) {
    BetterTogetherTransportModuleJNI.EndpointList_doAdd__SWIG_0(swigCPtr, this, IBTTransportEndpoint.getCPtr(x), x);
  }

  private void doAdd(int index, IBTTransportEndpoint x) {
    BetterTogetherTransportModuleJNI.EndpointList_doAdd__SWIG_1(swigCPtr, this, index, IBTTransportEndpoint.getCPtr(x), x);
  }

  private IBTTransportEndpoint doRemove(int index) {
    long cPtr = BetterTogetherTransportModuleJNI.EndpointList_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new IBTTransportEndpoint(cPtr, true);
  }

  private IBTTransportEndpoint doGet(int index) {
    long cPtr = BetterTogetherTransportModuleJNI.EndpointList_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new IBTTransportEndpoint(cPtr, true);
  }

  private IBTTransportEndpoint doSet(int index, IBTTransportEndpoint val) {
    long cPtr = BetterTogetherTransportModuleJNI.EndpointList_doSet(swigCPtr, this, index, IBTTransportEndpoint.getCPtr(val), val);
    return (cPtr == 0) ? null : new IBTTransportEndpoint(cPtr, true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    BetterTogetherTransportModuleJNI.EndpointList_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
