/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.skype;

public enum EndpointState {
  None,
  Connected,
  Disconnected;

  public final int swigValue() {
    return swigValue;
  }

  public static EndpointState swigToEnum(int swigValue) {
    EndpointState[] swigValues = EndpointState.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (EndpointState swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + EndpointState.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private EndpointState() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private EndpointState(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private EndpointState(EndpointState swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

