/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.skype;

public class IBTTransportStack {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IBTTransportStack(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IBTTransportStack obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BetterTogetherTransportModuleJNI.delete_IBTTransportStack(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static void createBTTransportStack(SWIGTYPE_p_ecsclient__IEcsClient ecsClient, SWIGTYPE_p_Microsoft__Applications__Telemetry_v5__ILogManager ariaLogManager, SWIGTYPE_p_http_stack__IHttpStack httpStack, StackInfo stackInfo) {
    BetterTogetherTransportModuleJNI.IBTTransportStack_createBTTransportStack(SWIGTYPE_p_ecsclient__IEcsClient.getCPtr(ecsClient), SWIGTYPE_p_Microsoft__Applications__Telemetry_v5__ILogManager.getCPtr(ariaLogManager), SWIGTYPE_p_http_stack__IHttpStack.getCPtr(httpStack), StackInfo.getCPtr(stackInfo), stackInfo);
  }

  public static IBTTransportStack getBTTransportStack() {
    long cPtr = BetterTogetherTransportModuleJNI.IBTTransportStack_getBTTransportStack();
    return (cPtr == 0) ? null : new IBTTransportStack(cPtr, false);
  }

  public static void destroyBTTransportStack() {
    BetterTogetherTransportModuleJNI.IBTTransportStack_destroyBTTransportStack();
  }

  public IBTTransportUser getBTTransportUser(SWIGTYPE_p_trouter__ITrouter trouter, IBTTransportUser.IAuthTokenCallback authCallBack, IBTTransportUser.IIncomingCommandListener commandListener, EndpointType endpointType, UserInfo userInfo) {
    long cPtr = BetterTogetherTransportModuleJNI.IBTTransportStack_getBTTransportUser(swigCPtr, this, SWIGTYPE_p_trouter__ITrouter.getCPtr(trouter), IBTTransportUser.IAuthTokenCallback.getCPtr(authCallBack), authCallBack, IBTTransportUser.IIncomingCommandListener.getCPtr(commandListener), commandListener, endpointType.swigValue(), UserInfo.getCPtr(userInfo), userInfo);
    return (cPtr == 0) ? null : new IBTTransportUser(cPtr, true);
  }

}
