/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.skype;

public class IBTTransportEndpoint {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected IBTTransportEndpoint(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IBTTransportEndpoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BetterTogetherTransportModuleJNI.delete_IBTTransportEndpoint(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setupSession(String causeId, String command, String commandDetails, IOutgoingCommandResponse commandResponseListener) {
    BetterTogetherTransportModuleJNI.IBTTransportEndpoint_setupSession(swigCPtr, this, causeId, command, commandDetails, IOutgoingCommandResponse.getCPtr(commandResponseListener), commandResponseListener);
  }

  public void sendCommand(String causeId, String command, String commandDetails, IOutgoingCommandResponse commandResponseListener) {
    BetterTogetherTransportModuleJNI.IBTTransportEndpoint_sendCommand(swigCPtr, this, causeId, command, commandDetails, IOutgoingCommandResponse.getCPtr(commandResponseListener), commandResponseListener);
  }

  public String getEndpointId() {
    return BetterTogetherTransportModuleJNI.IBTTransportEndpoint_getEndpointId(swigCPtr, this);
  }

  public EndpointType getEndpointType() {
    return EndpointType.swigToEnum(BetterTogetherTransportModuleJNI.IBTTransportEndpoint_getEndpointType(swigCPtr, this));
  }

  public EndpointState getEndpointState() {
    return EndpointState.swigToEnum(BetterTogetherTransportModuleJNI.IBTTransportEndpoint_getEndpointState(swigCPtr, this));
  }

  public void setSessionEstablished(boolean isEstablished) {
    BetterTogetherTransportModuleJNI.IBTTransportEndpoint_setSessionEstablished(swigCPtr, this, isEstablished);
  }

}
