/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.skype;

public class IBTTransportUser {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IBTTransportUser(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IBTTransportUser obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BetterTogetherTransportModuleJNI.delete_IBTTransportUser(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  static public class IAuthTokenCallback {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected IAuthTokenCallback(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(IAuthTokenCallback obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BetterTogetherTransportModuleJNI.delete_IBTTransportUser_IAuthTokenCallback(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    protected void swigDirectorDisconnect() {
      swigCMemOwn = false;
      delete();
    }
  
    public void swigReleaseOwnership() {
      swigCMemOwn = false;
      BetterTogetherTransportModuleJNI.IBTTransportUser_IAuthTokenCallback_change_ownership(this, swigCPtr, false);
    }
  
    public void swigTakeOwnership() {
      swigCMemOwn = true;
      BetterTogetherTransportModuleJNI.IBTTransportUser_IAuthTokenCallback_change_ownership(this, swigCPtr, true);
    }
  
    public void onTokenRequired(String oldToken) {
      BetterTogetherTransportModuleJNI.IBTTransportUser_IAuthTokenCallback_onTokenRequired(swigCPtr, this, oldToken);
    }
  
    public IAuthTokenCallback() {
      this(BetterTogetherTransportModuleJNI.new_IBTTransportUser_IAuthTokenCallback(), true);
      BetterTogetherTransportModuleJNI.IBTTransportUser_IAuthTokenCallback_director_connect(this, swigCPtr, true, true);
    }
  
  }

  public EndpointList discover() {
    return new EndpointList(BetterTogetherTransportModuleJNI.IBTTransportUser_discover(swigCPtr, this), true);
  }

  public void updateAuthToken(String authToken) {
    BetterTogetherTransportModuleJNI.IBTTransportUser_updateAuthToken(swigCPtr, this, authToken);
  }

  public EndpointList getEndpoints() {
    return new EndpointList(BetterTogetherTransportModuleJNI.IBTTransportUser_getEndpoints(swigCPtr, this), true);
  }

  static public class IIncomingCommandListener {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected IIncomingCommandListener(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(IIncomingCommandListener obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          BetterTogetherTransportModuleJNI.delete_IBTTransportUser_IIncomingCommandListener(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    protected void swigDirectorDisconnect() {
      swigCMemOwn = false;
      delete();
    }
  
    public void swigReleaseOwnership() {
      swigCMemOwn = false;
      BetterTogetherTransportModuleJNI.IBTTransportUser_IIncomingCommandListener_change_ownership(this, swigCPtr, false);
    }
  
    public void swigTakeOwnership() {
      swigCMemOwn = true;
      BetterTogetherTransportModuleJNI.IBTTransportUser_IIncomingCommandListener_change_ownership(this, swigCPtr, true);
    }
  
    public void onCommandReceived(IIncomingCommandRequest arg0, IIncomingCommandResponse arg1) {
      BetterTogetherTransportModuleJNI.IBTTransportUser_IIncomingCommandListener_onCommandReceived(swigCPtr, this, IIncomingCommandRequest.getCPtr(arg0), arg0, IIncomingCommandResponse.getCPtr(arg1), arg1);
    }
  
    public IIncomingCommandListener() {
      this(BetterTogetherTransportModuleJNI.new_IBTTransportUser_IIncomingCommandListener(), true);
      BetterTogetherTransportModuleJNI.IBTTransportUser_IIncomingCommandListener_director_connect(this, swigCPtr, true, true);
    }
  
  }

}
