/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.skype;

public class IIncomingCommandResponse {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected IIncomingCommandResponse(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IIncomingCommandResponse obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BetterTogetherTransportModuleJNI.delete_IIncomingCommandResponse(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStatus(long statusCode) {
    BetterTogetherTransportModuleJNI.IIncomingCommandResponse_setStatus(swigCPtr, this, statusCode);
  }

  public void setBody(String responseBody) {
    BetterTogetherTransportModuleJNI.IIncomingCommandResponse_setBody(swigCPtr, this, responseBody);
  }

  public ResponseSendStatusCode send() {
    return ResponseSendStatusCode.swigToEnum(BetterTogetherTransportModuleJNI.IIncomingCommandResponse_send(swigCPtr, this));
  }

}
