/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.skype;

public class IIncomingCommandRequest {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected IIncomingCommandRequest(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IIncomingCommandRequest obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BetterTogetherTransportModuleJNI.delete_IIncomingCommandRequest(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String getEndpointId() {
    return BetterTogetherTransportModuleJNI.IIncomingCommandRequest_getEndpointId(swigCPtr, this);
  }

  public String getCommand() {
    return BetterTogetherTransportModuleJNI.IIncomingCommandRequest_getCommand(swigCPtr, this);
  }

  public String getCommandDetails() {
    return BetterTogetherTransportModuleJNI.IIncomingCommandRequest_getCommandDetails(swigCPtr, this);
  }

  public String getCauseId() {
    return BetterTogetherTransportModuleJNI.IIncomingCommandRequest_getCauseId(swigCPtr, this);
  }

  public long getSequenceNumber() {
    return BetterTogetherTransportModuleJNI.IIncomingCommandRequest_getSequenceNumber(swigCPtr, this);
  }

}
