/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.skype;

public class IOutgoingCommandResponse {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IOutgoingCommandResponse(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IOutgoingCommandResponse obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BetterTogetherTransportModuleJNI.delete_IOutgoingCommandResponse(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    BetterTogetherTransportModuleJNI.IOutgoingCommandResponse_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    BetterTogetherTransportModuleJNI.IOutgoingCommandResponse_change_ownership(this, swigCPtr, true);
  }

  public void onRequestSucceeded(String causeId, String responseBody) {
    BetterTogetherTransportModuleJNI.IOutgoingCommandResponse_onRequestSucceeded(swigCPtr, this, causeId, responseBody);
  }

  public void onRequestFailed(String causeId, int errorCode, String errorDetails) {
    BetterTogetherTransportModuleJNI.IOutgoingCommandResponse_onRequestFailed(swigCPtr, this, causeId, errorCode, errorDetails);
  }

  public IOutgoingCommandResponse() {
    this(BetterTogetherTransportModuleJNI.new_IOutgoingCommandResponse(), true);
    BetterTogetherTransportModuleJNI.IOutgoingCommandResponse_director_connect(this, swigCPtr, true, true);
  }

}
