/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.skype;

public class StackInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StackInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StackInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BetterTogetherTransportModuleJNI.delete_StackInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String getUiVersion() {
    return BetterTogetherTransportModuleJNI.StackInfo_uiVersion_get(swigCPtr, this);
  }

  public String getPlatform() {
    return BetterTogetherTransportModuleJNI.StackInfo_platform_get(swigCPtr, this);
  }

  public String getAppId() {
    return BetterTogetherTransportModuleJNI.StackInfo_appId_get(swigCPtr, this);
  }

  public String getLanguageId() {
    return BetterTogetherTransportModuleJNI.StackInfo_languageId_get(swigCPtr, this);
  }

  public StackInfo(String uiVersion, String platform, String appId, String languageId) {
    this(BetterTogetherTransportModuleJNI.new_StackInfo__SWIG_0(uiVersion, platform, appId, languageId), true);
  }

  public StackInfo(String uiVersion, String platform, String appId) {
    this(BetterTogetherTransportModuleJNI.new_StackInfo__SWIG_1(uiVersion, platform, appId), true);
  }

  public StackInfo(String uiVersion, String platform) {
    this(BetterTogetherTransportModuleJNI.new_StackInfo__SWIG_2(uiVersion, platform), true);
  }

  public StackInfo(String uiVersion) {
    this(BetterTogetherTransportModuleJNI.new_StackInfo__SWIG_3(uiVersion), true);
  }

  public StackInfo() {
    this(BetterTogetherTransportModuleJNI.new_StackInfo__SWIG_4(), true);
  }

}
