/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.skype;

public class SWIGTYPE_p_http_stack__IHttpStack {
  private transient long swigCPtr;

  protected SWIGTYPE_p_http_stack__IHttpStack(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_http_stack__IHttpStack() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_http_stack__IHttpStack obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

