/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.skype;

public class UserInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected UserInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UserInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BetterTogetherTransportModuleJNI.delete_UserInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String getEndpointId() {
    return BetterTogetherTransportModuleJNI.UserInfo_endpointId_get(swigCPtr, this);
  }

  public String getUserId() {
    return BetterTogetherTransportModuleJNI.UserInfo_userId_get(swigCPtr, this);
  }

  public String getToken() {
    return BetterTogetherTransportModuleJNI.UserInfo_token_get(swigCPtr, this);
  }

  public String getTenant() {
    return BetterTogetherTransportModuleJNI.UserInfo_tenant_get(swigCPtr, this);
  }

  public String getRing() {
    return BetterTogetherTransportModuleJNI.UserInfo_ring_get(swigCPtr, this);
  }

  public UserInfo(String endpointId, String userId, String token, String tenant, String ring) {
    this(BetterTogetherTransportModuleJNI.new_UserInfo__SWIG_0(endpointId, userId, token, tenant, ring), true);
  }

  public UserInfo(String endpointId, String userId, String token, String tenant) {
    this(BetterTogetherTransportModuleJNI.new_UserInfo__SWIG_1(endpointId, userId, token, tenant), true);
  }

  public UserInfo(String endpointId, String userId, String token) {
    this(BetterTogetherTransportModuleJNI.new_UserInfo__SWIG_2(endpointId, userId, token), true);
  }

  public UserInfo(String endpointId, String userId) {
    this(BetterTogetherTransportModuleJNI.new_UserInfo__SWIG_3(endpointId, userId), true);
  }

  public UserInfo(String endpointId) {
    this(BetterTogetherTransportModuleJNI.new_UserInfo__SWIG_4(endpointId), true);
  }

  public UserInfo() {
    this(BetterTogetherTransportModuleJNI.new_UserInfo__SWIG_5(), true);
  }

}
